name: Deploy Frontend to EC2 mosque-match

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Install & Build Frontend (Next.js)
        run: |
          npm ci --legacy-peer-deps
          npm run build

      - name: Archive build files
        run: |
          tar -czf build.tar.gz .next public package.json package-lock.json

      - name: Upload build to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem build.tar.gz ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/tmp/

      - name: Extract & restart on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            mkdir -p /var/www/mosqueSearch-front
            tar -xzf /tmp/build.tar.gz -C /var/www/mosqueSearch-front
            cd /var/www/mosqueSearch-front
            npm install --omit=dev
            pm2 delete mosque-frontend || true
            pm2 start "npx next start -p 3000" --name mosque-frontend
            pm2 save
          EOF
