name: Deploy Frontend to EC2 mosque-match

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Install & Build Frontend (Next.js)
        run: |
          # Remove existing node modules and lock file
          rm -rf node_modules
          rm -f package-lock.json

          # Install dependencies with legacy peer deps
          npm install --legacy-peer-deps

          # Update lock file
          npm install --package-lock-only

          # Build the project
          npm run build

      - name: Deploy to EC2
        run: |
          scp -i key.pem -r .next public package.json ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/mosqueSearch-front

      - name: Restart Frontend on EC2
        run: |
          ssh -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/mosqueSearch-front
            pm2 restart mosque-frontend || pm2 start npm --name "mosque-frontend" -- start
          EOF
