name: Deploy Frontend to EC2 mosque-match

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Install & Build Frontend (Next.js)
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem -r .next public package.json package-lock.json ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/mosqueSearch-front

      - name: Restart Frontend on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/mosqueSearch-front
            npm ci --only=production
            pm2 delete mosque-frontend || true
            pm2 start npm --name "mosque-frontend" -- start -p 3000
          EOF
